
// Objective-C API for talking to the following Go packages
//
//	github.com/synycboom/tinyman-mobile-sdk/tinyman
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Tinyman_FRAMEWORK_H__
#define __Tinyman_FRAMEWORK_H__

#include "Tinyman.objc.h"
#include "Universe.objc.h"

#endif
